### ISSUE TITLE
Question: Any way to set line height?

### ISSUE THREAD

**Issue by khalidchawtany** [rhysd/NyaoVim#19]
I was looking for a way to set line-height and I did not find any.
I tried to put **CSS** rule in the Styles section of the **.nyaovimrc**. However, it didn't work.

Could you please elaborate on how to set line-height? if it is possible

Thanks for this great app. :+1:

**Comment by rhysd** [comment]
It should be set such as `:set lines=36' but currently can't.  This is because Neovim GUI frontend is started after Neovim is initialized.
We're discussing in https://github.com/neovim/neovim/issues/3901 and new frontend architecture will hopefully solve this issue in Neovim 0.2.

As a workaround, I think you can specify lines by calcurating it from `height` and `font-size`.

```html
<!-- lines = 900 / 15 = 60 -->
<neovim-editor height="900" font-size="15"></neovim-editor>
```

**Comment by rhysd** [comment]
Sorry, I misunderstood line-heigt for 'height of lines'...
Currently we can't specify line-height, but we're discussing about it in https://github.com/rhysd/neovim-component/issues/13.

**Comment by khalidchawtany** [comment]
Thanks, feel free to close this issue as I will try to follow the conversation over there :)

**Comment by rhysd** [comment]
NyaoVim 0.0.10 supports line-height.  Please try it :)

https://github.com/rhysd/NyaoVim#configure-gui-options

**Comment by khalidchawtany** [comment]
Lovely :) 
Many thanks :+1:

**Comment by metalelf0** [comment]
Wow! This is great! Awesome work! :) :) :+1:
