### ISSUE TITLE
Discussion: file loading & runtime path

### ISSUE THREAD

**Issue by romgrk** [rhysd/NyaoVim#20]
Hello,

I was wondering if you would oppose loading `.js` files directly from `./nyaovim-plugin` directories through `require()`? 
If not, I can send a PR, I have it ready locally.

(Oh and by the way, never make the mistake of doing `npm install electron`; it's the second time I get trapped by that sucker.)

**Comment by rhysd** [comment]
Hmm,  `nyaovim-plugin` directory includes Web Component HTML file.  It provides an abstracted component and users can put it to `nyaovimrc.html` freely with CSS.

You're supposing a plugin which contains only JavaScript code (it means no UI)?


> `npm install electron`

Yeah, it's confusing.  But package name seemed to be already reserved...

**Comment by romgrk** [comment]
I know Nyao is still under development, but have you had time to think more thoroughly of file loading and user configuration?

I ask the question because I find myself jumping back and forth through `nyaovim`, `neovim-component`,`~/.config/nvim/nyaovim-plugin` and `~/.config/nyaovim` whenever I need to make some modification or configure some option. I also find myself directly editing `nyaovim` and `neovim-component` files rather than writing my own separate config files. 

One last point, what about a runtime path for `nyaovim`? I have various html/css/bower_components/node_modules that are shared amongst various apps that I'd be happy to import.

**Comment by rhysd** [comment]
> I ask the question because I find myself jumping back and forth through nyaovim, neovim-component,~/.config/nvim/nyaovim-plugin and ~/.config/nyaovim whenever I need to make some modification or configure some option.

Hmm, what are you writing to files in `~/.config/nvim/nyaovim-plugin` directory?  I suppose `nyaovim-plugin` is for UI plugins, not for user configuration.  I'm thinking it's the best to make users edit `~/.config/nyaovim/nyaovimrc.html`,  although currently it is not realized as you said in #22.

> I also find myself directly editing nyaovim and neovim-component files rather than writing my own separate config files.

I think that's because NyaoVim lacks (many) configuration points yet.  I want to add more ability to configure NyaoVim.  If you have some requests/suggestions,  please write it as issue.  It's helpful :smile:

> One last point, what about a runtime path for nyaovim?

Exactly the load path (`require` for Node.js, HTML and CSS) is not written in documentation.  I'll add them to documentation and notify you in this issue.

**Comment by romgrk** [comment]
Ok thanks! I've seen some commits on `RuntimeApi` but I haven't had time to look into that, although it looked like the kind of things I'd love to have!

About the `~/.config/nvim/nyaovim-plugin` directory:
I am perfectly aware of that, but it feels way cleaner to have all my nvim files in the same place, although I know it is not intended for that…

**Comment by romgrk** [comment]
Another point I´d like to insist on, despite having already mentioned it:
I do not like having an `.html` file as an entry point. I'd be much more comfortable with a `.js`.
It is akin to the `node-webkit` vs `electron` divergence. `Node-webkit` enters on `.html` files, while `electron` enters on `.js` files. HTML is «supposed» to be for UI rendering, while JS is for code. But I won't insist more on this point, if you choose to go with `nyaovimrc.html` I´ll go with that.

**Comment by rhysd** [comment]
> I am perfectly aware of that, but it feels way cleaner to have all my nvim files in the same place, although I know it is not intended for that…

I can agree that.  But `~/.config/nvim` is not available because it is used for Neovim and we can't put our config file there.  

> I do not like having an .html file as an entry point. I'd be much more comfortable with a .js.

`require()` your JavaScript file is available via [runtime API](https://github.com/rhysd/NyaoVim/blob/master/docs/runtime-api.md).  You can put your JS file at favorite place and load it from `init.vim` as below.

```vim
nyaovim#require_javascript_file('/path/to/your/javascript_file.js')
```

Please note that I don't intend that JavaScript is used for configuration.

**Comment by rhysd** [comment]
Additionally, you can use `<script>` tag in `nyaovimrc.html`.

Because there is no limit (e.g. CORS) such as web application,  you can simply load *any* JavaScript file using `<script>`, I think.

```html
<script src="file:///path/to/your/javascript_file.js"></script>
```

Of course relative path is also available.

```html
<script src="javascript_file.js"></script>
```

**Comment by romgrk** [comment]
Yeah, I had done some experiments with `<script>` tags, actually it's efficient enough, and placing them at the end of the `nyaovimrc.html` ensures they are loaded after everything.

(Oh and btw, I haven't said yet but the whole neovim-component/nyaovim is really a great work!)

**Comment by rhysd** [comment]
I'm glad to hear that!  I'll add new tip about `<script>`.

**Comment by rhysd** [comment]
@romgrk 

Can we close this issue?

**Comment by romgrk** [comment]
Yep, sure

**Comment by rhysd** [comment]
Thanks!
