### ISSUE TITLE
Allow user-defined settings for BrowserWindow

### ISSUE THREAD

**Issue by romgrk** [rhysd/NyaoVim#22]
It would be nice to be able to define these locally.
https://github.com/rhysd/NyaoVim/blob/master/main/main.ts#L88-L95

Ideas/suggestions:
- for `width` and `height`, maybe use `localStorage`? Therefore window dimension could be preserved through sessions.
- for non-OSX, it is nice having `autoHideMenuBar: true` and/or `frame: false`

**Comment by rhysd** [comment]
Thank you for your suggestion :smile:  Yeah, I'm also considering this.

> for width and height, maybe use localStorage? Therefore window dimension could be preserved through sessions.

I think LocalStorage is not suitable because LocalStorage only can be referred from renderer process.  BrowserWindow is created in main process.  So, if we decided to use LocalStorage, the sequence would be

1. Create browser window with `show: false`
2. Set config values from renderer process via ipc
3. Show window

It may makes start up slow.  In addition, we must prepare user interface to set config values to LocalStorage.

I thought JSON config file might be suitable,  but it is also not good to add new another config file.  So I deferred to implement this feature until good idea comes...

**Comment by romgrk** [comment]
Yeah, I was thinking more of something like a cache file for preserving window state through sessions. I haven't played that much with electron _& al_ but something if there is some equivalent for applications it would be good. (I know every electron-opened application creates and stores files in my `~/.cache` automatically)

**Comment by rhysd** [comment]
Yes, I want to make configuration as easy as possible.  However,  it is a Electron app structure problem that window configuration can't be put in local storage or `nyaovimrc.html`.

I thought about this and currently have 2 ideas.

1. Add `~/.config/nyaovim/guiconf.json` and users can write window configurations to it.  It can also include properties of `<neovim-editor>`.  So users can write all neovim editor config values to the JSON file.  But this increases the number of config files...

2. Wait Neovim 0.2.  At 0.2, Neovim frontend architecture will be changed.  (The detail is https://github.com/equalsraf/neovim-qt/issues/50 .)  Although I don't know the architecture yet (because it's being implemented), I think below sequence will be available and users (hopefully) can write GUI configurations to `init.vim` directly as Vim script settings.  But I can't guess when Neovim 0.2 is released...
  1.  `nvim` starts
  2. `nvim` loads `init.vim` config
  3. `nvim` spawns `nyaovim` frontend binary
  4. `nyaovim` loads config from `nvim` process via rpc
  5. `nyaovim` opens a window with the config

As you said, because NyaoVim is under development, it may be good to start implementation of 1. without waiting 2. (if 2. is added we can simply discard the JSON file loading architecture and shift to 2. idea).

**Comment by rhysd** [comment]
I added this as [browser-config.json](https://github.com/rhysd/NyaoVim/blob/master/docs/browser-config.md) feature.

**Comment by romgrk** [comment]
Yes I saw, thanks!
