### ISSUE TITLE
CLI command run in the foreground

### ISSUE THREAD

**Issue by RobertAudi** [rhysd/NyaoVim#26]
I am not sure if this is normal at this stage of development, but when I launch NyaoVim from the command line using `nyaovim`, everything seems to work, but the terminal is "waiting". In other words, if I press `C-c` it kills the process and closes the app, `C-z` puts the process in the background and the main window is not accessible, etc.

I could write a wrapper script but I'm not sure if this is a bug or a Work In Progress side effect:

```sh
#!/bin/sh

if test -t 1; then
  exec 1>/dev/null
fi

if test -t 2; then
  exec 2>/dev/null
fi

command nyaovim "$@" &
```

**Comment by rhysd** [comment]
It's expected behavior for now.  The same as other many command line tools, `nyaovim` is executed in foreground.  And `&` is available to execute NyaoVim in background.

However, as you wondered,  we might detach the spawned Electron process as `open -a`.  In that case, error log may be lost.  But it is better to detach the process as default behavior and add `--no-detach` option.

**Comment by RobertAudi** [comment]
Thanks for the clarification. Should I close this issue then? Or should we add the "feature" label?

**Comment by rhysd** [comment]
Both gVim in Linux and MacVim in OS X detach an editor process.  And I think it is better for GUI apps to detach its process.  So I'll implement this and then close this issue.

**Comment by RobertAudi** [comment]
Works perfectly! Thanks :+1:
