### ISSUE TITLE
Azerty

### ISSUE THREAD

**Issue by JodusNodus** [rhysd/NyaoVim#29]
As an azerty keyboard user i use the alt key a lot to access characters. But in Nyaovim the key mapping is wrong for some characters including back slash, curly and square brackets,  and more ... instead of getting the character that was requested it results in some variation of the character "ü".

**Comment by rhysd** [comment]
Hmm...  This looks similar to #10.  You're using OS X, aren't you?  Please describe your environment (OS, NyaoVim version).

> it results in some variation of the character "ü".

Input "ü" is derived from OS X's keyboard feature.  Alt key is mapped to option key in OS X and option+{char} inputs the special characters.  But [I added workaround for this issue](https://github.com/rhysd/neovim-component/blob/884e7ddfbd4d617727864eefd3ab63d194a24fc7/src/neovim/input.ts#L249)

Could you please cooperate with me for debugging?

1. Start NyaoVim with `$ NODE_ENV=debug nyaovim`.  (Chrome DevTools will also start.)
2. Open 'console' tab of DevTools.
3. Enter the input which causes this issue.
4. Log includes 'Keydown event:' output and it shows `keydown` event for your input.  Could you take a screenshot of the event value?

**Comment by JodusNodus** [comment]
I am using Os X 10.11 on a macbook pro with an azerty keyboard. The nyaovim version is 0.0.17.
Pressing the alt key in combination with another key results in the event with the right keycode and the "Input to neovim" also results in the right key.

<img width="695" alt="screen shot 2016-02-23 at 17 57 37" src="https://cloud.githubusercontent.com/assets/14956282/13259284/0085bc2c-da57-11e5-982d-0190c94ab8b6.png">

**Comment by rhysd** [comment]
Thank you for the screenshot, very helpful.

Hmm..., if the input `<A-{>` is correct, NyaoVim sends correct input to `nvim`.  Doesn't this problem occur in console `nvim` editor?

**Comment by JodusNodus** [comment]
I use neovim daily in iterm2 and all the key-maps work perfectly.

**Comment by rhysd** [comment]
Let me ask a question about azerty layout.

You entered the `+ = }` key with `alt` key in [this picture](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Azerty_fr_laptop.svg/2000px-Azerty_fr_laptop.svg.png) and you intended to input `}` to Neovim, right?

**Comment by JodusNodus** [comment]
Well, Not exactly. The macbook's have a different variation on the azerty keyboard. [Picture](http://ecx.images-amazon.com/images/I/71AzlASSbTL._SL1500_.jpg)
I haven't tested it with a normal azerty keyboard so i can't say if that works. I have to press  <Alt-(> to insert a curly bracket.

**Comment by rhysd** [comment]
> I haven't tested it with a normal azerty keyboard so i can't say if that works. I have to press to insert a curly bracket.

Yea, it's no problem.  What I want to solve is a problem you reported:wink:.  So please tell me about your environment because I don't have any azerty keyboard.

- Which keys did you enter in your picture?
- What input did you expect to Neovim?  (What is input to screen if it were in console `nvim`?)

**Comment by JodusNodus** [comment]
In terminal neovim, or any other application i have to press `<Alt-(>` to insert `{`.
I have a lot of neovim plugins installed but that doesn't seem to be the problem because a clean neovim install + nyaovim has the same problem.

**Comment by rhysd** [comment]
OK, I understood this problem.

Input to neovim must be `{` but actually it was `<A-{>`.

Currently I don't know how to fix this (similar to #10) because browser can't know the keyboard layout.  In case of console `nvim`, modifier key is handled correctly by terminal and `nvim` receives correct input `{`.

I can add a config for workaround.  If the config is set to 'on', NyaoVim simply ignores Alt key.  But I don't know it is useful.

**Comment by JodusNodus** [comment]
That makes sense, if i have some free time i will give it a shot. But for now i'll just use terminal neovim.

**Comment by JodusNodus** [comment]
I just tried `nvim-qt` and the same problem occurs there.

**Comment by rhysd** [comment]
Thank you for the comment.

OK, I'll try adding workaround option to `browser-config.json` to solve this issue and #10.  If enabling the workaround, NyaoVim simply ignores alt key and keyboard can use it as their modifier key and `<A-x>` key mappings won't work.

**Comment by rhysd** [comment]
I added new property `disable-alt-key` to `<neovim-editor>` component in `~/.config/nyaovim/nyaovimrc.html`.  If this property is on, NyaoVim ignores alt key input so that keyboard which uses alt key as special modifier is available.  Please note that `<A-x>` mapping will be unavailable.

```html
<neovim-editor
  id="nyaovim-editor"
  argv$="[[argv]]"
  font="Monaco,monospace"
  font-size="14"
  line-height="1.5"
  disable-alt-key
></neovim-editor>
```

To use this, please reinstall `nyaovim` package and ensure version of`neovim-component` package is `0.4.4`.  (NyaoVim depends on it)

**Comment by JodusNodus** [comment]
Thanks a lot :+1: 
The workaround does the job for me. Should we close the issue?

**Comment by rhysd** [comment]
Yes, thank you for your confirmation!
